/**
 * This file is autogenerated by syncContracts script.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  "11155111": {
    "FHECounter": {
      "address": "0x2fe30b50376a3DfAD116F5d646a58c80099EF72b",
      "abi": [
        {
          "inputs": [
            {
              "internalType": "externalEuint32",
              "name": "inputEuint32",
              "type": "bytes32"
            },
            {
              "internalType": "bytes",
              "name": "inputProof",
              "type": "bytes"
            }
          ],
          "name": "decrement",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "getCount",
          "outputs": [
            {
              "internalType": "euint32",
              "name": "",
              "type": "bytes32"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "externalEuint32",
              "name": "inputEuint32",
              "type": "bytes32"
            },
            {
              "internalType": "bytes",
              "name": "inputProof",
              "type": "bytes"
            }
          ],
          "name": "increment",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "protocolId",
          "outputs": [
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "stateMutability": "pure",
          "type": "function"
        }
      ],
      "inheritedFunctions": {},
      "deployedOnBlock": 0
    },
    "PrivateRPS": {
      "address": "0x12f725DFb080b8cB5B8AE0b7BC98DEE26B7EBC51",
      "abi": [
        {
          "inputs": [],
          "stateMutability": "nonpayable",
          "type": "constructor"
        },
        {
          "inputs": [],
          "name": "InvalidKMSSignatures",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "NoHandleFoundForRequestID",
          "type": "error"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "account",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "amount",
              "type": "uint256"
            }
          ],
          "name": "Claimed",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "uint256",
              "name": "requestID",
              "type": "uint256"
            }
          ],
          "name": "DecryptionFulfilled",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "uint256",
              "name": "requestID",
              "type": "uint256"
            },
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            }
          ],
          "name": "DecryptionRequested",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "recipient",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "fee",
              "type": "uint256"
            }
          ],
          "name": "FeePaid",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "playerA",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "enum PrivateRPS.MatchMode",
              "name": "mode",
              "type": "uint8"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "stake",
              "type": "uint256"
            },
            {
              "indexed": false,
              "internalType": "uint64",
              "name": "deadline",
              "type": "uint64"
            }
          ],
          "name": "MatchCreated",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "playerB",
              "type": "address"
            }
          ],
          "name": "MatchJoined",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "enum PrivateRPS.State",
              "name": "state",
              "type": "uint8"
            },
            {
              "indexed": false,
              "internalType": "address",
              "name": "winner",
              "type": "address"
            }
          ],
          "name": "MatchResolved",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "player",
              "type": "address"
            }
          ],
          "name": "MoveSubmitted",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "player",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "address",
              "name": "winner",
              "type": "address"
            }
          ],
          "name": "WinnerAttested",
          "type": "event"
        },
        {
          "inputs": [],
          "name": "attestGrace",
          "outputs": [
            {
              "internalType": "uint64",
              "name": "",
              "type": "uint64"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            },
            {
              "internalType": "address",
              "name": "winnerAddr",
              "type": "address"
            }
          ],
          "name": "attestWinner",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "",
              "type": "bytes32"
            },
            {
              "internalType": "address",
              "name": "",
              "type": "address"
            }
          ],
          "name": "attestedWinner",
          "outputs": [
            {
              "internalType": "address",
              "name": "",
              "type": "address"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            }
          ],
          "name": "claim",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "externalEuint8",
              "name": "encMove",
              "type": "bytes32"
            },
            {
              "internalType": "bytes",
              "name": "inputProof",
              "type": "bytes"
            },
            {
              "internalType": "enum PrivateRPS.MatchMode",
              "name": "mode",
              "type": "uint8"
            },
            {
              "internalType": "uint256",
              "name": "stake",
              "type": "uint256"
            },
            {
              "internalType": "uint64",
              "name": "deadline",
              "type": "uint64"
            }
          ],
          "name": "createAndCommit",
          "outputs": [
            {
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            }
          ],
          "stateMutability": "payable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            }
          ],
          "name": "expireCreated",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            }
          ],
          "name": "expireLocked",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "feeRecipient",
          "outputs": [
            {
              "internalType": "address",
              "name": "",
              "type": "address"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            },
            {
              "internalType": "address",
              "name": "winnerAddr",
              "type": "address"
            }
          ],
          "name": "finalizeWinner",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            }
          ],
          "name": "getEncryptedOutcome",
          "outputs": [
            {
              "internalType": "bytes32",
              "name": "winnerHandle",
              "type": "bytes32"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "enum PrivateRPS.MatchMode",
              "name": "mode",
              "type": "uint8"
            },
            {
              "internalType": "uint256",
              "name": "stake",
              "type": "uint256"
            }
          ],
          "name": "getPendingMatchCount",
          "outputs": [
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "enum PrivateRPS.MatchMode",
              "name": "mode",
              "type": "uint8"
            },
            {
              "internalType": "uint256",
              "name": "stake",
              "type": "uint256"
            },
            {
              "internalType": "uint256",
              "name": "offset",
              "type": "uint256"
            },
            {
              "internalType": "uint256",
              "name": "limit",
              "type": "uint256"
            }
          ],
          "name": "getPendingMatches",
          "outputs": [
            {
              "internalType": "bytes32[]",
              "name": "matchIds",
              "type": "bytes32[]"
            },
            {
              "internalType": "uint256",
              "name": "total",
              "type": "uint256"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            }
          ],
          "name": "getStatus",
          "outputs": [
            {
              "internalType": "enum PrivateRPS.State",
              "name": "state",
              "type": "uint8"
            },
            {
              "internalType": "address",
              "name": "playerA",
              "type": "address"
            },
            {
              "internalType": "address",
              "name": "playerB",
              "type": "address"
            },
            {
              "internalType": "uint256",
              "name": "stake",
              "type": "uint256"
            },
            {
              "internalType": "uint64",
              "name": "deadline",
              "type": "uint64"
            },
            {
              "internalType": "enum PrivateRPS.MatchMode",
              "name": "mode",
              "type": "uint8"
            },
            {
              "internalType": "address",
              "name": "winner",
              "type": "address"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            },
            {
              "internalType": "externalEuint8",
              "name": "encMove",
              "type": "bytes32"
            },
            {
              "internalType": "bytes",
              "name": "inputProof",
              "type": "bytes"
            }
          ],
          "name": "joinAndCommit",
          "outputs": [],
          "stateMutability": "payable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "",
              "type": "bytes32"
            },
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "name": "matchQueue",
          "outputs": [
            {
              "internalType": "bytes32",
              "name": "",
              "type": "bytes32"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "",
              "type": "bytes32"
            }
          ],
          "name": "matches",
          "outputs": [
            {
              "internalType": "address",
              "name": "playerA",
              "type": "address"
            },
            {
              "internalType": "address",
              "name": "playerB",
              "type": "address"
            },
            {
              "internalType": "uint256",
              "name": "stake",
              "type": "uint256"
            },
            {
              "internalType": "uint64",
              "name": "deadline",
              "type": "uint64"
            },
            {
              "internalType": "enum PrivateRPS.MatchMode",
              "name": "mode",
              "type": "uint8"
            },
            {
              "internalType": "enum PrivateRPS.State",
              "name": "state",
              "type": "uint8"
            },
            {
              "internalType": "euint8",
              "name": "moveA",
              "type": "bytes32"
            },
            {
              "internalType": "euint8",
              "name": "moveB",
              "type": "bytes32"
            },
            {
              "internalType": "address",
              "name": "winner",
              "type": "address"
            },
            {
              "internalType": "eaddress",
              "name": "winnerEnc",
              "type": "bytes32"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "maxDeadlineDelta",
          "outputs": [
            {
              "internalType": "uint64",
              "name": "",
              "type": "uint64"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "maxStake",
          "outputs": [
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "minStake",
          "outputs": [
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "uint256",
              "name": "requestID",
              "type": "uint256"
            },
            {
              "internalType": "bytes",
              "name": "cleartexts",
              "type": "bytes"
            },
            {
              "internalType": "bytes",
              "name": "decryptionProof",
              "type": "bytes"
            }
          ],
          "name": "onDecryption",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "owner",
          "outputs": [
            {
              "internalType": "address",
              "name": "",
              "type": "address"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "protocolId",
          "outputs": [
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "stateMutability": "pure",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "rakeBps",
          "outputs": [
            {
              "internalType": "uint16",
              "name": "",
              "type": "uint16"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "relayer",
          "outputs": [
            {
              "internalType": "address",
              "name": "",
              "type": "address"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "name": "requestIdToMatchId",
          "outputs": [
            {
              "internalType": "bytes32",
              "name": "",
              "type": "bytes32"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "bytes32",
              "name": "matchId",
              "type": "bytes32"
            }
          ],
          "name": "resolve",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "uint64",
              "name": "_sec",
              "type": "uint64"
            }
          ],
          "name": "setAttestGrace",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "uint16",
              "name": "_rakeBps",
              "type": "uint16"
            },
            {
              "internalType": "address",
              "name": "_feeRecipient",
              "type": "address"
            }
          ],
          "name": "setFeeParams",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "uint64",
              "name": "_maxDelta",
              "type": "uint64"
            }
          ],
          "name": "setMaxDeadlineDelta",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "_relayer",
              "type": "address"
            }
          ],
          "name": "setRelayer",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "uint256",
              "name": "_minStake",
              "type": "uint256"
            },
            {
              "internalType": "uint256",
              "name": "_maxStake",
              "type": "uint256"
            }
          ],
          "name": "setStakeRange",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "stateMutability": "payable",
          "type": "receive"
        }
      ],
      "inheritedFunctions": {},
      "deployedOnBlock": 0
    }
  }
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
